### ISSUE TITLE
[FEAT] Wallet 구현하기

### ISSUE THREAD

**Issue by YoonBaek** [YoonBaek/CryptoProject#18]
## FEATURE
- [x] Wallet 구현하기
## TASKS
- [x] Singleton 패턴 wallet 인스턴스 생성
- [x] 신규 wallet 생성 및 저장
- [x] 지갑 주소 구현
- [x] wallet 복구 및 transaction에 wallet 적용
- [x] 서명 (signature) 구현
- [x] 검증 (verifying) 구현
## TIL
- Wallet은 Key(pv + pub)와 주소로 구성되어 있다.
- byte 형태로 지갑 정보를 저장하고 다시 restore할 수 있다.
- signature의 r과 s, 그리고 pubkey의 x,y는 모두 bigInt이기 때문에 byte형태로 만들어 파일로 저장해준다.

**Comment by YoonBaek** [comment]
All Done!
