### ISSUE TITLE
[FEAT] 블록체인에 작업증명 적용하기

### ISSUE THREAD

**Issue by YoonBaek** [YoonBaek/CryptoProject#4]
## FEATURE
- [x] 내 블록체인 네트워크에 작업 증명 적용하기
## TASKS
- [x] 블록 채굴 어렵게 만들기
- [x] 블록 채굴 난이도 부여
- [x] 채굴 난이도 자동화1
- [x] API로 자동화 작동 여부 확인
## Others
-

**Comment by YoonBaek** [comment]
All Done
